# information for running the gun but also for naming the file!
/control/alias NSHOTS 1000
/control/alias FLUX_NAME IMCC_5TeV_A_200m
/control/alias DETECTOR MuColl_v1,0,1 # name the geoemtry you'd like to use
# NB: Root gets upset by dots, so version names need to use commas. Sorry.

# This doesn't name the file, but it is useful for controlling the biasing
/control/alias MUNUNUCBIAS 1e6
/control/alias ELNUNUCBIAS 1e6
/control/alias NUELECBIAS 1e6

#______________________________________________________________________________
/physics_lists/nu/NuDetectorName target
# Still need to define where the detector is so that we can define where the
# biasing is to happen.

/detector/readGDML ../{DETECTOR}.gdml

/run/initialize
# Initializing the gun allows the worker threads to build the gun

/gun/position 0 0 -6000
# Position is in millimeters!
# For simulating up to the interaction point and sampling at IQF1_1, this is
# 6 meters before the interaction point, so we move our generator back 6 meters.

# Allows dynamic filenaming, meaning we can assign unique runs unique names
# automatically based on their run parameters
/analysis/setFileName {FLUX_NAME}_{NSHOTS}_{DETECTOR}


/custom/biasing/MuNuNucleusBias {MUNUNUCBIAS}
/custom/biasing/ElNuNucleusBias {ELNUNUCBIAS}
/custom/biasing/NuElectronBias {NUELECBIAS}
# This allows us to set biasing at runtime without the need to recompile the
# simulation code. It must be after the initialization of the run, otherwise the
# script will attempt to bias before the command to do so has been created.
/generator/mode flux
/generator/fluxFile ../{FLUX_NAME}.root
/run/beamOn {NSHOTS}
