import os
import numpy as np
import matplotlib.pyplot as plt

try:
    import uproot
except ImportError:
    raise ImportError("Install uproot with 'pip install uproot awkward matplotlib numpy' to run this script.")

ROOT_FILE = "neutrino.root"
TREE_NAME = "tree"

PLOT_DIR = "plots"
os.makedirs(PLOT_DIR, exist_ok=True)

SENTENCES = {
    "cc_vs_nc": "This plot validates the CC/NC classification performance from the Geant4 event action: a realistic sample should show both charged-current and neutral-current interactions, with CC dominating for \u03BD_\u03BC at 20 GeV but NC still clearly present.",
    "interaction_model": "The interaction-model breakdown checks whether the implementation distinguishes QE, RES, and DIS correctly; I expect a mix of QE/RES at low hadronic multiplicity and DIS rising as the available hadronic energy increases.",
    "outgoing_lepton_energy": "The outgoing lepton energy spectrum is a direct physics crosscheck: CC events should produce a visible muon peak while NC events should not have an associated charged lepton.",
    "outgoing_hadron_energy": "Hadronic energy deposition helps confirm that NC interactions produce visible hadronic activity even though the primary neutrino exits the event undetected.",
    "q2_xbj": "The Q2 vs x_Bj distribution probes the kinematics reconstruction in the CC implementation and allows us to compare the event sample against expectations from deep inelastic and resonant scattering.",
    "secondary_multiplicity": "Secondary multiplicity is a sanity check on event topology: CC and NC interactions should both produce nonzero secondary counts, with DIS showing larger multiplicity than QE.",
    "secondary_track_length": "Total secondary track length validates tracking and hadronic shower development: neutrino interactions should produce long cumulative track lengths in DIS-like events and shorter totals in QE-like events.",
    "em_shower_activity": "The electromagnetic shower variables test whether the simulation correctly produces photons and electrons from hadronic cascades and neutral-current pi0 production.",
    "hadronic_multiplicity": "The hadronic multiplicity plot validates that the event action captures nucleon and pion production correctly: NC and CC hadronic final states should show significant proton/neutron and pion counts.",
    "nu_interaction_process": "The primary neutrino interaction-process breakdown shows whether Geant4 is selecting the expected neutrino-nucleus channels and whether the event action records the correct physics process.",
    "secondary_creator_process": "The secondary creator-process distribution checks whether the secondaries are being generated by the expected physics modules, such as hadronic production, decay, and electromagnetic processes.",
}


def load_tree(filename=ROOT_FILE, tree_name=TREE_NAME):
    with uproot.open(filename) as f:
        tree = f[tree_name]
        data = tree.arrays(library="np")
    return data


def plot_cc_vs_nc(data):
    values = np.zeros(2, dtype=int)
    values[0] = np.count_nonzero(data["isCC"])
    values[1] = np.count_nonzero(data["isNC"])
    labels = ["CC", "NC"]

    fig, ax = plt.subplots(figsize=(6, 5))
    ax.bar(labels, values, color=["#1f77b4", "#ff7f0e"])
    ax.set_ylabel("Event count")
    ax.set_title("Charged Current vs Neutral Current")
    ax.grid(axis="y", alpha=0.3)
    fig.tight_layout()
    fig.savefig(os.path.join(PLOT_DIR, "cc_vs_nc.png"))
    plt.close(fig)
    print(SENTENCES["cc_vs_nc"])


def plot_nu_interaction_process(data):
    proc = data.get("nuInteractionProcess")
    if proc is None or len(proc) == 0:
        return

    mask = np.array([(p is not None) and str(p).strip() not in ["", "None"] for p in proc])
    proc = proc[mask]
    if proc.size == 0:
        return

    names, counts = np.unique(proc, return_counts=True)
    order = np.argsort(counts)[::-1]
    names = names[order]
    counts = counts[order]
    n_events = proc.size
    rates = counts / n_events

    print("\nPrimary neutrino interaction rates per interacting event:")
    for name, rate in zip(names, rates):
        print(f"{name:25s}  {rate:.4e}")

    fig, ax = plt.subplots(figsize=(8, 5))
    ax.bar(names, rates, color="#7f7f7f", edgecolor="black")
    ax.set_ylabel("Interactions per event")
    ax.set_title("Primary Neutrino Interaction Processes per Event")
    ax.set_xticklabels(names, rotation=45, ha="right")
    ax.grid(axis="y", alpha=0.3)
    ax.set_yscale("log")
    fig.tight_layout()
    fig.savefig(os.path.join(PLOT_DIR, "nu_interaction_process.png"))
    plt.close(fig)
    print(SENTENCES["nu_interaction_process"])


def plot_interaction_model(data):
    labels = ["QE", "RES", "DIS", "Other", "Unknown"]
    counts = [0] * len(labels)
    model = data.get("interactionModel")
    if model is None:
        return
    for i, label in enumerate(labels):
        counts[i] = np.count_nonzero(model == label)

    fig, ax = plt.subplots(figsize=(7, 5))
    ax.bar(labels, counts, color=["#2ca02c", "#d62728", "#9467bd", "#8c564b", "#7f7f7f"])
    ax.set_ylabel("Event count")
    ax.set_title("Interaction Model Breakdown")
    ax.grid(axis="y", alpha=0.3)
    fig.tight_layout()
    fig.savefig(os.path.join(PLOT_DIR, "interaction_model.png"))
    plt.close(fig)
    print(SENTENCES["interaction_model"])


def plot_outgoing_lepton_energy(data):
    mask_cc = data["isCC"] == 1
    energies = data["outgoingLeptonE"][mask_cc]

    fig, ax = plt.subplots(figsize=(7, 5))
    ax.hist(energies / 1e3, bins=40, histtype="stepfilled", color="#1f77b4", alpha=0.8)
    ax.set_xlabel("Outgoing lepton energy [GeV]")
    ax.set_ylabel("CC event count")
    ax.set_title("Outgoing Lepton Energy in CC Events")
    ax.grid(alpha=0.3)
    fig.tight_layout()
    fig.savefig(os.path.join(PLOT_DIR, "outgoing_lepton_energy.png"))
    plt.close(fig)
    print(SENTENCES["outgoing_lepton_energy"])


def plot_outgoing_hadron_energy(data):
    hadronE = data["outgoingHadronE"]

    fig, ax = plt.subplots(figsize=(7, 5))
    ax.hist(hadronE / 1e3, bins=40, color="#9467bd", alpha=0.8)
    ax.set_xlabel("Outgoing hadronic energy [GeV]")
    ax.set_ylabel("Event count")
    ax.set_title("Outgoing Hadronic Energy")
    ax.grid(alpha=0.3)
    fig.tight_layout()
    fig.savefig(os.path.join(PLOT_DIR, "outgoing_hadron_energy.png"))
    plt.close(fig)
    print(SENTENCES["outgoing_hadron_energy"])


def plot_q2_xbj(data):
    mask = data["isCC"] == 1
    q2 = data["Q2"][mask]
    xbj = data["xBj"][mask]
    valid = np.isfinite(q2) & np.isfinite(xbj) & (q2 > 0) & (xbj > 0)
    q2 = q2[valid]
    xbj = xbj[valid]

    if q2.size == 0:
        print("No valid CC kinematic points available for Q2/xBj plot.")
        return

    fig, ax = plt.subplots(figsize=(7, 6))
    h = ax.hist2d(xbj, q2 / 1e6, bins=50, cmap="viridis", normed=False)
    fig.colorbar(h[3], ax=ax, label="Event count")
    ax.set_xlabel("xBj")
    ax.set_ylabel("Q^2 [GeV^2]")
    ax.set_title("Q^2 vs xBj for CC Events")
    ax.set_xscale("log")
    ax.set_yscale("log")
    fig.tight_layout()
    fig.savefig(os.path.join(PLOT_DIR, "q2_xbj.png"))
    plt.close(fig)
    print(SENTENCES["q2_xbj"])


def plot_secondary_multiplicity(data):
    nsec = data["nSecondaries"]

    fig, ax = plt.subplots(figsize=(7, 5))
    ax.hist(nsec, bins=np.arange(nsec.min(), nsec.max() + 2) - 0.5, color="#17becf", edgecolor="black")
    ax.set_xlabel("Number of secondary tracks")
    ax.set_ylabel("Event count")
    ax.set_title("Secondary Multiplicity")
    ax.grid(axis="y", alpha=0.3)
    fig.tight_layout()
    fig.savefig(os.path.join(PLOT_DIR, "secondary_multiplicity.png"))
    plt.close(fig)
    print(SENTENCES["secondary_multiplicity"])


def plot_secondary_track_length(data):
    length = data.get("secTrackLength")
    if length is None:
        return

    fig, ax = plt.subplots(figsize=(7, 5))
    ax.hist(length, bins=40, color="#17becf", alpha=0.8)
    ax.set_xlabel("Total secondary track length [mm]")
    ax.set_ylabel("Event count")
    ax.set_title("Total Secondary Track Length")
    ax.grid(alpha=0.3)
    fig.tight_layout()
    fig.savefig(os.path.join(PLOT_DIR, "secondary_track_length.png"))
    plt.close(fig)
    print(SENTENCES["secondary_track_length"])


def plot_em_shower_activity(data):
    ngamma = data.get("nGamma", np.zeros(0, dtype=int))
    ne = data.get("nElectron", np.zeros(0, dtype=int))
    npos = data.get("nPositron", np.zeros(0, dtype=int))
    if len(ngamma) == 0 or len(ne) == 0 or len(npos) == 0:
        return
    em_count = ngamma + ne + npos

    fig, ax = plt.subplots(figsize=(7, 5))
    ax.hist(em_count, bins=np.arange(em_count.min(), em_count.max() + 2) - 0.5, color="#ff7f0e", edgecolor="black")
    ax.set_xlabel("EM secondary count (gamma + e^- + e^+)")
    ax.set_ylabel("Event count")
    ax.set_title("Electromagnetic Shower Activity")
    ax.grid(axis="y", alpha=0.3)
    fig.tight_layout()
    fig.savefig(os.path.join(PLOT_DIR, "em_shower_activity.png"))
    plt.close(fig)
    print(SENTENCES["em_shower_activity"])


def plot_secondary_creator_process(data):
    creator = data.get("step_creatorproc")
    if creator is None or len(creator) == 0:
        return

    event_counts = {}
    n_events = len(creator)
    for row in creator:
        counts = {}
        for item in row:
            if item and item != "Primary":
                counts[item] = counts.get(item, 0) + 1
        for item, cnt in counts.items():
            event_counts[item] = event_counts.get(item, 0) + cnt

    if len(event_counts) == 0:
        return

    names = []
    avg_per_event = []
    for item, total in sorted(event_counts.items(), key=lambda kv: -kv[1]):
        names.append(item)
        avg_per_event.append(total / n_events)

    print("\nSecondary creator process rates per event:")
    for name, rate in zip(names, avg_per_event):
        print(f"{name:25s}  {rate:.4e}")

    fig, ax = plt.subplots(figsize=(8, 5))
    ax.bar(names, avg_per_event, color="#9467bd", edgecolor="black")
    ax.set_ylabel("Average count per event")
    ax.set_title("Secondary Creator Process Count per Event")
    ax.set_xticklabels(names, rotation=45, ha="right")
    ax.grid(axis="y", alpha=0.3)
    ax.set_yscale("log")
    fig.tight_layout()
    fig.savefig(os.path.join(PLOT_DIR, "secondary_creator_process.png"))
    plt.close(fig)
    print(SENTENCES["secondary_creator_process"])


def plot_hadronic_multiplicity(data):
    nprotons = data.get("nProtonSec", np.zeros(0, dtype=int))
    nneutrons = data.get("nNeutron", np.zeros(0, dtype=int))
    npions = data.get("nPionPlus", np.zeros(0, dtype=int)) + data.get("nPionMinus", np.zeros(0, dtype=int)) + data.get("nPionZero", np.zeros(0, dtype=int))
    if len(nprotons) == 0 or len(nneutrons) == 0:
        return
    hadronic_count = nprotons + nneutrons + npions

    fig, ax = plt.subplots(figsize=(7, 5))
    ax.hist(hadronic_count, bins=np.arange(hadronic_count.min(), hadronic_count.max() + 2) - 0.5, color="#2ca02c", edgecolor="black")
    ax.set_xlabel("Hadronic secondary count (p+n+\pi)")
    ax.set_ylabel("Event count")
    ax.set_title("Hadronic Multiplicity")
    ax.grid(axis="y", alpha=0.3)
    fig.tight_layout()
    fig.savefig(os.path.join(PLOT_DIR, "hadronic_multiplicity.png"))
    plt.close(fig)
    print(SENTENCES["hadronic_multiplicity"])


def plot_vertex_distribution(data):
    fig, ax = plt.subplots(figsize=(7, 5))
    ax.hist2d(data["vertexZ"], data["vertexX"], bins=60, cmap="plasma")
    fig.colorbar(label="Events")
    ax.set_xlabel("Vertex Z [mm]")
    ax.set_ylabel("Vertex X [mm]")
    ax.set_title("Primary Interaction Vertex Distribution")
    fig.tight_layout()
    fig.savefig(os.path.join(PLOT_DIR, "vertex_distribution.png"))
    plt.close(fig)
    print("This vertex distribution checks that the neutrino interactions are being recorded in the expected target region and not from unrelated boundary interactions.")


def main():
    data = load_tree()
    plot_cc_vs_nc(data)
    plot_nu_interaction_process(data)
    plot_interaction_model(data)
    plot_outgoing_lepton_energy(data)
    plot_outgoing_hadron_energy(data)
    plot_q2_xbj(data)
    plot_secondary_multiplicity(data)
    plot_secondary_track_length(data)
    plot_em_shower_activity(data)
    plot_secondary_creator_process(data)
    plot_hadronic_multiplicity(data)
    plot_vertex_distribution(data)
    print(f"Saved plots in: {os.path.abspath(PLOT_DIR)}")


if __name__ == "__main__":
    main()
