# ==============================
# --- Physics list settings ---
# ==============================



# Read your GDML detector description
/detector/readGDML /workspace/neutrino_demo/output.gdml

#/physics_lists/em/addNeutrino

#/physics_lists/nu/NuDetectorName DeafultRegionForTheWorld
/physics_lists/nu/NuDetectorName target
/physics_lists/nu/NeutrinoActivation true
/physics_lists/nu/NuETotXscActivation true
/physics_lists/nu/NuEleCcBias 1
/physics_lists/nu/NuEleNcBias 1
/physics_lists/nu/NuNucleusBias 1e10
#/physics_lists/nu/NuOscDistanceName tgtosc
#/physics_lists/nu/NuOscDistanceBias 1





# ==============================
# --- Primary particle gun ---
# ==============================
/gun/particle nu_mu
/gun/energy 20 GeV
#/gun/direction 0 0 1
/gun/position 0 0 0 cm
#/run/initialize
#/tracking/storeTrajectory 0                                                                                                                   


# ==============================
# --- Run ---
# ==============================
/run/printProgress 1
/run/setCut 1 mm
#/tracking/verbose 1       # Increase tracking verbosity
#/process/verbose 2        
#/run/verbose 1

/run/initialize
/run/beamOn 20

# EM / other processes
#/physics_lists/em/SyncRadiation true
#/physics_lists/em/SyncRadiationAll true
#/physics_lists/em/GammaNuclear true
#/physics_lists/em/UseGammaNuclearXS false
#/physics_lists/em/LENDGammaNuclear false
#/physics_lists/em/ElectroNuclear true
#/physics_lists/em/MuonNuclear false
#/physics_lists/em/GammaToMuons false
#/physics_lists/em/PositronToMuons true
#/physics_lists/em/PositronToHadrons true

# Optional conversion factors (uncomment to use)
#/physics_lists/em/GammaToMuonsFactor 1.0
#/physics_lists/em/PositronToMuonsFactor 1.0
#/physics_lists/em/PositronToHadronsFactor 1.0

# ==============================
# --- Visualization ---
# ==============================
#/vis/open OGL
#/vis/viewer/set/viewpointThetaPhi 90 180
#/vis/scene/add/trajectories
#/vis/scene/add/axes 0 0 0 10 cm
